In [2]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)
print(type(arr))

[[1, 2], [3, 4]]
<class 'list'>


In [3]:
import numpy as np

# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [5]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [6]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [7]:
np.random.rand(2, 2)

array([[0.97061303, 0.30464006],
       [0.15233547, 0.37124682]])

In [8]:
torch.rand(2, 2)

tensor([[0.2828, 0.0093],
        [0.6909, 0.3112]])

In [9]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [13]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [18]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [19]:
# Numpy array
np_array = np.ones((2, 2))

print(np_array)

[[1. 1.]
 [1. 1.]]


In [20]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [21]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [22]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

In [23]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [24]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [25]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [26]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [28]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [29]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [30]:
torch_tensor = torch.ones(2, 2)
type(torch_tensor)

torch.Tensor

In [32]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

In [33]:
torch_to_numpy = torch_tensor.numpy()

type(torch_to_numpy)

numpy.ndarray

In [34]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [35]:
# CPU to GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor_cpu.to(device)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [36]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

In [38]:
a = torch.ones(2, 2)
print(a)
print(a.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [39]:
a.view(4)

tensor([1., 1., 1., 1.])

In [40]:
a.view(4).size()

torch.Size([4])

In [41]:
a = torch.ones(2, 2)
print(a)
b = torch.ones(2, 2)
print(b)
# Element-wise addition
c = a + b
print(c)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


In [42]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [43]:
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


In [45]:
print(a)
print(b)
a - b

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


tensor([[0., 0.],
        [0., 0.]])

In [46]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [47]:
# Inplace
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [48]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [49]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [50]:
# Not in-place
print(torch.mul(a, b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [51]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [52]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [53]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [54]:
torch.div(b, a)

tensor([[0., 0.],
        [0., 0.]])

In [55]:
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

In [58]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [59]:
a.mean(dim=0)

tensor(5.5000)

In [60]:
a.mean(dim=1) 
# Here we get an error because the tensor is of size 10 and not 10x1 so there's no second dimension to calculate.

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [61]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

a.size()

torch.Size([2, 10])

In [64]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

In [65]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)